let password = prompt("What's gonna be the password?");
let url = prompt("What's the website url?");
var input = createElement("input",{"id":"myInput"});
var input = document.createElement("input",{"id":"myInput","type":"text"});
var text = document.getElementById("myInput");
text.value = "javascript:let passwordInput = prompt(" + '"What is the password?"' + ");if (passwordInput == " + '""' + ") {  alert("+'"Nice try!"' + ");} else if (passwordInput != " + '"' + password + '"' + ") {  alert(" + '"Nice try!"'+");} else {  window.location.replace("+ '"' + url + '"' +");};";
text.select();
navigator.clipboard.writeText(text.value);
document.getElementById("myInput").remove();
let response = alert("Copied!");
